export const programs = [
  {
    name: 'EasyRetro',
    description: 'Simple, Intuitive and Engaging Retrospectives',
    url: 'https://easyretro.io',
    programUrl: 'https://easyretro.io/affiliate-program',
    commission: 20,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'CSS Pro',
    logo: 'https://csspro.com/apple-touch-icon.png',
    description: 'A re-imagined Devtools for web design',
    url: 'https://csspro.com',
    programUrl: 'https://csspro.gumroad.com/affiliates',
    commission: 20,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'Senja',
    logo: 'https://framerusercontent.com/images/FKXyQKfcgQzBRcrolOI4cjpNGwk.png',
    description: 'Collect, Manage and Share Testimonials',
    url: 'https://senja.io',
    programUrl: 'https://senja.io/affiliates',
    commission: 30,
    lifetime: 'recurring',
    category: 'testimonial',
  },
  {
    name: 'Testimonial',
    logo: 'https://testimonial.to/logo192.png',
    description: 'Get testimonials from your customers with ease',
    url: 'https://testimonial.to/',
    programUrl: 'https://testimonial.to/affiliates',
    commission: 30,
    lifetime: 'recurring',
    category: 'testimonial',
  },
  {
    name: 'Photo AI',
    description: 'Take photographs with AI',
    url: 'https://photoai.com',
    programUrl: 'https://photo-ai.getrewardful.com',
    commission: 20,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'Video Tap',
    description: 'Get more out of the videos your already made',
    url: 'https://videotapit.com',
    programUrl: 'https://video-tap.getrewardful.com',
    commission: 50,
    lifetime: 'recurring',
    category: 'marketing',
  },
  {
    name: 'OneUp',
    logo: 'https://www.oneupapp.io/img/oneup-square.png',
    description: 'Schedule your social media posts',
    url: 'https://www.oneupapp.io',
    programUrl: 'https://oneup.getrewardful.com',
    commission: 20,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'GummySearch',
    logo: 'https://gummysearch.com/favicon-32x32.png?v=67578bfc454efc4eee525a3b92778838',
    description: 'Audience Research tool for Reddit',
    url: 'https://gummysearch.com/',
    programUrl: 'https://gummysearch.getrewardful.com',
    commission: 20,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'HeadshotPro',
    description: 'Professional corporate headshots',
    url: 'https://www.headshotpro.com/',
    programUrl: 'https://headshotpro-1.getrewardful.com/',
    commission: 20,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'Super Send',
    description: 'Automate outbound cold outreach',
    url: 'https://supersend.io/',
    programUrl: 'https://super-send.getrewardful.com',
    commission: 30,
    lifetime: '12',
    category: 'social',
  },
  {
    name: 'Tally',
    description: 'The simplest way to create forms',
    url: 'https://tally.so',
    programUrl: 'https://tally.so/help/affiliate-program',
    commission: 20,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'Transistor FM',
    logo: 'https://transistor.fm/assets/seo/favicon.ico',
    description: 'Podcast hosting and analytics platform.',
    url: 'https://transistor.fm',
    programUrl: 'https://affiliates.transistor.fm',
    commission: 25,
    lifetime: 'recurring',
    category: 'hosting',
  },
  {
    name: 'Typefully',
    logo: 'https://typefully.com/icon/favicon.ico',
    description:
      'Distraction-free editor to write & publish tweets and threads',
    url: 'https://typefully.app',
    programUrl: 'https://help.typefully.com/affiliate',
    commission: 20,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'Closet Tools',
    description:
      'Poshmark Bot - Make more sales, get more followers, and spend less time sharing',
    url: 'https://closet.tools',
    programUrl: 'https://closet.tools/affiliate',
    commission: 30,
    lifetime: 'recurring',
    category: 'marketplace',
  },
  {
    name: 'Geekbot',
    description: 'Automated standup meetings in Slack',
    url: 'https://geekbot.com',
    programUrl: 'https://geekbot.com/affiliates',
    commission: 20,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'Low Fruits',
    description: 'Find untapped keywords today to rank faster',
    url: 'https://lowfruits.io',
    programUrl: 'https://lowfruits.io/affiliate',
    commission: 20,
    lifetime: 'recurring',
    category: 'seo',
  },
  {
    name: 'Also Asked',
    description: 'Find the questions people also ask',
    url: 'https://alsoasked.com',
    programUrl: 'https://alsoasked.getrewardful.com',
    commission: 20,
    lifetime: 'recurring',
    category: 'seo',
  },
  {
    name: 'Rewardful',
    logo: 'https://uploads-ssl.webflow.com/6041705a8ccb775007a2e651/6049b263ec3e5affbea8b06b_rw.png',
    description: 'Launch Your Affiliate Program With Ease',
    url: 'https://rewardful.com/',
    programUrl: 'https://friends.rewardful.com',
    commission: 25,
    lifetime: '12',
    category: 'affiliate',
  },
  {
    name: 'Tweet Hunter',
    logo: 'https://uploads-ssl.webflow.com/62753f70ab07d3b66d844be5/62753f70ab07d30c6e844c5d_Group%20252%20(1).png',
    description: 'Build & Monetize Your Twitter Audience',
    url: 'https://tweethunter.io/',
    programUrl: 'https://tweethunter.getrewardful.com',
    commission: 30,
    lifetime: 'recurrent',
    category: 'social',
  },
  {
    name: 'Feather',
    logo: 'https://feather.so/images/white-bg-144.png',
    description: 'Notion to Blog in minutes',
    url: 'https://feather.so/',
    programUrl: 'https://feather.getrewardful.com',
    commission: 25,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'InstantChapters',
    logo: 'https://uploads-ssl.webflow.com/64134c0d2c6dd8473537268d/6420f5c2e6ce553182125e8e_InstantChapters256.png',
    description: 'Timestamped Chapters For Your YouTube Videos',
    url: 'https://instantchapters.com/',
    programUrl: 'https://instantchapters.getrewardful.com',
    commission: 30,
    lifetime: '12',
    category: 'social',
  },
  {
    name: 'BannerBear',
    logo: 'https://www.bannerbear.com/images/favicon-96x96.png',
    description: 'Automate & Scale Your Marketing',
    url: 'https://www.bannerbear.com/',
    programUrl: 'https://bannerbear.getrewardful.com',
    commission: 30,
    lifetime: 'recurring',
    category: 'marketing',
  },
  {
    name: 'Copy AI',
    logo: 'https://assets-global.website-files.com/628288c5cd3e8411b90a36a4/629a3335c7b473c21eb68773_icon-2.png',
    description: 'Whatever you want to ask, our chat has the answers',
    url: 'https://www.copy.ai/',
    programUrl: 'https://copyai.getrewardful.com',
    commission: 45,
    lifetime: '12',
    category: 'ai',
  },
  {
    name: 'Swipe Files',
    logo: 'https://global-uploads.webflow.com/5e693ac2f06874ddd11d3e26/5e6a58aea5ebb5e65a4431bc_Webclip.png',
    description:
      'Cutting edge, occasionally crazy marketing ideas to grow your SaaS',
    url: 'https://swipefiles.co/',
    programUrl: 'https://swipefiles.getrewardful.com',
    commission: 25,
    lifetime: 'recurring',
    category: 'marketing',
  },
  {
    name: 'Copymatic',
    logo: 'https://copymatic.ai/wp-content/uploads/2022/04/cropped-favicon-1-192x192.png',
    description: 'Generate Content, Copy & Images with AI',
    url: 'https://copymatic.ai/',
    programUrl: 'https://copymatic.getrewardful.com',
    commission: 30,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'Sprintful',
    logo: 'https://sprintful-website.s3.amazonaws.com/logo.svg',
    description: '3-Click Appointment Scheduling',
    url: 'https://sprintful.com/',
    programUrl: 'https://sprintful.getrewardful.com',
    commission: 20,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'SignWell',
    logo: 'https://www.signwell.com/assets/favicon-171eb9fed1d7aa9cc1c5885b4ff9cd5afb0c412855c617ea858dcd704153bf20.ico',
    description:
      'Make it so easy to sign your documents that it cuts turnaround time in half',
    url: 'https://www.signwell.com/',
    programUrl: 'https://signwell.getrewardful.com',
    commission: 25,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'EverBee',
    logo: 'https://everbee.io/wp-content/uploads/2021/09/cropped-Wordpress-Everbee-Favicon-512-x-512-px-192x192.png',
    description: 'Find The Best Products To Sell On Etsy In Seconds',
    url: 'https://www.everbee.io/',
    programUrl: 'https://everbee.getrewardful.com',
    commission: 30,
    lifetime: '12',
    category: 'marketplace',
  },
  {
    name: 'SavvyCal',
    logo: 'https://savvycal.com/apple-touch-icon.png',
    description: 'The thoughtful way to find a time to meet',
    url: 'https://savvycal.com/',
    programUrl: 'https://savvycal.getrewardful.com',
    commission: 25,
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'EmailOctopus',
    description: 'Manage and email your subscribers for far cheaper',
    url: 'https://emailoctopus.com/',
    programUrl: 'https://emailoctopus.com/affiliates',
    commission: 30,
    lifetime: 'recurring',
    category: 'marketing',
  },
  {
    name: 'T.LY',
    description: "World's Shortest Link Shortener service",
    url: 'https://t.ly',
    programUrl: 'https://t.ly/affiliate',
    commission: 20,
    lifetime: '12',
    category: 'productivity',
  },
  {
    name: 'MemberSpace',
    logo: 'https://www.memberspace.com/wp-content/uploads/2022/11/cropped-favicon-192x192.png',
    description: 'Launch your membership site',
    url: 'https://www.memberspace.com',
    programUrl: 'https://www.memberspace.com/affiliates/',
    commission: 25,
    lifetime: 'recurring',
    category: 'affiliate',
  },
  {
    name: 'ChatBase',
    description: 'Custom ChatGPT for your data',
    url: 'https://www.chatbase.co/',
    programUrl: 'https://chatbase-co.getrewardful.com',
    commission: 20,
    lifetime: '12',
    category: 'ai',
  },
  {
    name: 'CopyLime',
    logo: 'https://copylime.com/assets/images/favicon.svg',
    description: 'Write 1000+ words in ~60 seconds',
    url: 'https://copylime.com/',
    programUrl: 'https://copylime.com/partners',
    commission: 30,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'AI Lawyer',
    logo: 'https://super-static-assets.s3.amazonaws.com/b9a6147f-080d-4048-8b84-3159a3bd3683/uploads/favicon/5e4ecd47-fab9-4af6-92fc-aff1857a729a.png',
    description: 'Personal AI lawyer at your fingertips',
    url: 'https://ailawyer.pro/',
    programUrl: 'https://ailawyer.pro/earn-with-ai-lawyer',
    commission: 15,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'ILO',
    logo: 'https://ilo.so/static/favicon.png',
    description: 'A little app to help you get big on Twitter',
    url: 'https://ilo.so/',
    programUrl: 'https://ilo.so/affiliates/',
    commission: 25,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'Interaxai',
    description: 'No-Code Monetizable and Embeddable AI Widgets',
    url: 'https://interaxai.com/',
    programUrl: 'https://interaxai.com/affiliate',
    commission: 10,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'Typing Mind',
    logo: 'https://www.typingmind.com/apple-icon-152x152.png',
    description: 'A better UI for ChatGPT',
    url: 'https://www.typingmind.com/',
    programUrl: 'https://tdinh.lemonsqueezy.com/affiliates',
    commission: 59,
    lifetime: 'onceoff',
    category: 'ai',
  },
  {
    name: 'My Ask AI',
    logo: 'https://d1muf25xaso8hp.cloudfront.net/https%3A%2F%2F7ac07acbae116a5155080d295197d8d6.cdn.bubble.io%2Ff1680092618447x871663073292272500%2FZapier%2520logo.png?w=128&h=&auto=compress&dpr=1&fit=max',
    description:
      'Create your own ChatGPT, add your content, launch it anywhere',
    url: 'https://myaskai.com/',
    programUrl: 'https://affiliates.reflio.com/invite/myaskai',
    commission: 25,
    type: 'percentage',
    lifetime: 'onceoff',
    category: 'ai',
  },
  {
    name: 'SideBird',
    description: 'Stop chasing Twitter followers. Get fans',
    url: 'https://www.sidebird.io/',
    programUrl: 'https://affiliates.reflio.com/invite/sidebird',
    commission: 30,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'Birdy',
    logo: 'https://birdy.so/purple-bird-twemoji.svg',
    description: 'Get more Twitter followers',
    url: 'https://birdy.so',
    programUrl: 'https://affiliates.reflio.com/invite/birdy',
    commission: 30,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'Tiiny Host',
    description: 'The simplest way to host & share your web project',
    url: 'https://tiiny.host',
    programUrl: 'https://tiiny.host/affiliates',
    commission: 20,
    lifetime: 'recurring',
    category: 'hosting',
  },
  {
    name: 'Carrd',
    description:
      'Simple, free, fully responsive one-page sites for pretty much anything',
    url: 'https://carrd.co',
    programUrl: 'https://carrd.co/docs/account/referral-program',
    commission: 30,
    lifetime: 'recurring',
    category: 'hosting',
  },
  {
    name: 'Leave Me Alone',
    logo: 'https://leavemealone.com/favicons/apple-icon-120x120.png',
    description: 'Easily unsubscribe from emails',
    url: 'https://leavemealone.com/',
    programUrl: 'https://leavemealone.com/friends/',
    commission: 30,
    lifetime: '12',
    category: 'productivity',
  },
  {
    name: 'PostSheet',
    logo: 'https://postsheet.com/apple-touch-icon-114x114-precomposed.png',
    description: 'Effortlessly send personalized emails & text messages',
    url: 'https://postsheet.com/',
    programUrl: 'https://postsheet.com/affiliate',
    commission: 25,
    lifetime: 'recurring',
    category: 'marketing',
  },
  {
    name: 'ContentBot',
    logo: 'https://contentbot.ai/assets/img/newbrandfav.png?v=2',
    description: 'AI Automation At Its Best',
    url: 'https://contentbot.ai',
    programUrl: 'https://contentbot.ai/partners',
    commission: 30,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'MagickPen',
    logo: 'https://d29lra7z8g0m3a.cloudfront.net/2e8f597f-4bd5-4be0-bee9-4242ca2465e1/img/favicon.png',
    description: 'Powered by AI, let me be your intelligent writing assistant',
    url: 'https://store.magickpen.com/',
    programUrl: 'https://store.magickpen.com/affiliates',
    commission: 72,
    lifetime: 'onceoff',
    category: 'ai',
  },
  {
    name: 'Hivoe',
    logo: 'https://www.hivoe.com/apple-touch-icon.png',
    description: 'Qualified Twitter leads in your inbox — on autopilot',
    url: 'https://www.hivoe.com',
    programUrl: 'https://www.hivoe.com/affiliates',
    commission: 30,
    lifetime: 'recurring',
    category: 'ai',
  },
  {
    name: 'FameWall',
    logo: 'https://ucarecdn.com/87f090c7-36c4-470f-9ac7-dff8e97cd59b/',
    description: 'Use Social Proof to increase sales for your business',
    url: 'https://famewall.io/',
    programUrl: 'https://affiliates.reflio.com/invite/famewall',
    commission: 25,
    lifetime: 'recurring',
    category: 'testimonial',
  },
  {
    name: 'Pallyy',
    logo: 'https://pallyy.com/favicon.png',
    description:
      'Social media management platform for growing brands and agencies',
    url: 'https://pallyy.com/',
    programUrl: 'https://pallyy.getrewardful.com/signup',
    commission: 40,
    lifetime: 'recurring',
    category: 'social',
  },
  {
    name: 'Kat Links',
    logo: 'https://katlinks.io/wp-content/uploads/2021/04/katlinks-icon.png',
    description:
      'Rank Higher and Get More Traffic with an affordable SEO Tool 🚀',
    url: 'https://katlinks.io',
    programUrl: 'https://katlinks.io/affiliate-program/',
    commission: 30,
    lifetime: 'recurring',
    category: 'seo',
  },
  {
    name: 'Kat Links',
    logo: 'https://katlinks.io/wp-content/uploads/2021/04/katlinks-icon.png',
    description:
      'Rank Higher and Get More Traffic with an affordable SEO Tool 🚀',
    url: 'https://katlinks.io',
    programUrl: 'https://katlinks.io/affiliate-program/',
    commission: 30,
    lifetime: 'recurring',
    category: 'seo',
  },
  {
    name: 'Pirsch',
    logo: 'https://pirsch.io/static/img/favicon/apple-touch-icon.png',
    description: "It's How Analytics Should Be",
    url: 'https://pirsch.io/',
    programUrl: 'https://docs.pirsch.io/affiliate',
    commission: 6,
    lifetime: 'onceoff',
    category: 'marketing',
  },
  {
    name: 'Snappa',
    logo: 'https://snappa.com/public/ico/favicon.ico',
    description: 'Create online graphics in a snap',
    url: 'https://snappa.com',
    programUrl: 'https://snappa.com/affiliates',
    commission: 6,
    type: 'fixed',
    lifetime: 'recurring',
    category: 'productivity',
  },
  {
    name: 'TrackDesk',
    description: 'Do More With Your Affiliate Tracking Software',
    url: 'https://trackdesk.com',
    programUrl: 'https://trackdesk.com/affiliate-program',
    commission: 30,
    lifetime: 'recurring',
    category: 'affiliate',
  },
  {
    name: 'Imitate Email',
    description: 'The easiest way to see how the embedded email viewer works',
    url: 'https://imitate.email/',
    programUrl: 'https://imitate.email/affiliates',
    commission: 40,
    lifetime: '12',
    category: 'productivity',
  },
]
