export const programs = [
  {
    name: 'EasyRetro',
    logo: 'easyretro.svg',
    description: 'Simple, Intuitive and Engaging Retrospectives',
    url: 'https://easyretro.io',
    programUrl: 'https://easyretro.io/affiliate-program',
    commission: 20,
  },
  {
    name: 'Senja',
    logo: 'senja.webp',
    description: 'Collect, Manage and Share Testimonials',
    url: 'https://senja.io',
    programUrl: 'https://senja.io/affiliates',
    commission: 30,
  },
  {
    name: 'Testimonial',
    logo: 'testimonial.svg',
    description: 'Get testimonials from your customers with ease',
    url: 'https://testimonial.io/',
    programUrl: 'https://testimonial.to/affiliates',
    commission: 30,
  },
  {
    name: 'Photo AI',
    logo: 'photoai.svg',
    description: 'Take photographs with AI',
    url: 'https://photoai.com',
    programUrl: 'https://photo-ai.getrewardful.com',
    commission: 20,
    category: 'ai',
  },
  {
    name: 'Video Tap',
    logo: 'videotap.png',
    description: 'Get more out of the videos your already made',
    url: 'https://videotapit.com',
    programUrl: 'https://video-tap.getrewardful.com',
    commission: 50,
  },
  {
    name: 'OneUp',
    logo: 'oneup.png',
    description: 'Schedule your social media posts',
    url: 'https://www.oneupapp.io',
    programUrl: 'https://oneup.getrewardful.com',
    commission: 20,
    category: 'social',
  },
  {
    name: 'GummySearch',
    logo: 'gummy.png',
    description: 'Audience Research tool for Reddit',
    url: 'https://gummysearch.com/',
    programUrl: 'https://gummysearch.getrewardful.com',
    commission: 20,
  },
  {
    name: 'HeadshotPro',
    logo: 'headshot.svg',
    description: 'Professional corporate headshots',
    url: 'https://www.headshotpro.com/',
    programUrl: 'https://headshotpro-1.getrewardful.com/',
    commission: 20,
    category: 'ai',
  },
  {
    name: 'Super Send',
    logo: 'supersend.png',
    description:
      'Automate outbound cold outreach across linkedin, twitter, and email',
    url: 'https://supersend.io/',
    programUrl: 'https://super-send.getrewardful.com',
    commission: 30,
    timeframe: '12 payments',
    category: 'social',
  },
  {
    name: 'Tally',
    logo: 'tally.png',
    description: 'The simplest way to create forms',
    url: 'https://tally.so',
    programUrl: 'https://tally.so/help/affiliate-program',
    commission: 20,
  },
  {
    name: 'Transistor FM',
    logo: 'transistor.svg',
    description: 'Podcast hosting and analytics platform.',
    url: 'https://transistor.fm',
    programUrl: 'https://affiliates.transistor.fm',
    commission: 25,
  },
  {
    name: 'Typefully',
    logo: 'typefully.svg',
    description:
      'Distraction-free editor to write & publish tweets and threads',
    url: 'https://typefully.app',
    programUrl: 'https://help.typefully.com/affiliate',
    commission: 20,
    category: 'social',
  },
  {
    name: 'Closet Tools',
    logo: 'closet.svg',
    description:
      'Poshmark Bot - Make more sales, get more followers, and spend less time sharing',
    url: 'https://closet.tools',
    programUrl: 'https://closet.tools/affiliate',
    commission: 30,
  },
  {
    name: 'Geekbot',
    logo: 'geekbot.png',
    description: 'Automated standup meetings in Slack',
    url: 'https://geekbot.com',
    programUrl: 'https://geekbot.com/affiliates',
    commission: 20,
  },
]
